# Operating system (build VM template)
os: Visual Studio 2015

# clone directory
clone_folder: c:\projects

install:
  - cd c:\projects
  - ps: Start-FileDownload 'http://openrtm.org/pub/Windows/OpenRTM-aist/1.1/OpenRTM-aist-1.1.2-RELEASE_x86_64.msi'
  - ps: msiexec /i OpenRTM-aist-1.1.2-RELEASE_x86_64.msi /qn /l*v install.log
  - ps: env
  - ps: type install.log

build:

# scripts to run before build
before_build:
  - cd c:\projects
  - set RTM_VC_VERSION=14
  - mkdir build
  - cd build
  - cmake ..
