os: Visual Studio 2015

platform: x64

clone_folder: c:\projects

environment:
  RTM_VC_VERSION: vc14

install:
  - ps: Start-FileDownload 'http://openrtm.org/pub/Windows/OpenRTM-aist/1.1/OpenRTM-aist-1.1.2-RELEASE_x86_64.msi'
  - reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" /f /v "ConsentPromptBehaviorAdmin" /t REG_DWORD /d "0"
  - reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" /f /v "PromptOnSecureDesktop" /t REG_DWORD /d "0"
  - reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" /f /v "EnableLUA" /t REG_DWORD /d "0"
  - reg add "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" /f /v "FilterAdministratorToken" /t REG_DWORD /d "1"
  - ps: Restart-Computer -Force -ErrorAction SilentlyContinue
  - ps: Start-Sleep -s 10
  - start /wait msiexec /i OpenRTM-aist-1.1.2-RELEASE_x86_64.msi /qn /norestart /leawi "install.log"
  - ps: Restart-Computer -Force -ErrorAction SilentlyContinue
  - ps: Start-Sleep -s 10
  - appveyor-retry choco install doxygen
  - env
  - type install.log

build:

before_build:
  - mkdir build && cd build
  - cmake -G"Visual Studio 14 Win64" ..
  - cmake --build . --config Release
