matrix:
  allow_failures:
    - os: Visual Studio 2015
      RTM_VC_VERSION: vc14
      RTM_CMAKE_VC_VERSION: "Visual Studio 14 Win64"
    - os: Visual Studio 2013
      RTM_VC_VERSION: vc12
      RTM_CMAKE_VC_VERSION: "Visual Studio 12 Win64"

platform: x64

clone_folder: c:\projects

configuration:
  - Debug
  - Release

cache:
    - c:\projects\OpenRTM-aist-1.1.2-RELEASE_x86_64.msi

install:
  - ps: Start-FileDownload 'http://openrtm.org/pub/Windows/OpenRTM-aist/1.1/OpenRTM-aist-1.1.2-RELEASE_x86_64.msi'
  - start /wait msiexec /i OpenRTM-aist-1.1.2-RELEASE_x86_64.msi /qn /forcerestart /le "install.log"
#  - ps: Start-Sleep -s 10
  - choco install doxygen.install
  - env
  - type install.log

build:

before_build:
  - mkdir build && cd build
  - cmake -G "{RTM_CMAKE_VC_VERSION}" ..
