# Operating system (build VM template)
os: Visual Studio 2015

platform: x64

# clone directory
clone_folder: c:\projects

environment:
  RTM_VC_VERSION: 14

install:
  - ps: Start-FileDownload 'http://openrtm.org/pub/Windows/OpenRTM-aist/1.1/OpenRTM-aist-1.1.2-RELEASE_x86_64.msi'
#  - ps: msiexec /i OpenRTM-aist-1.1.2-RELEASE_x86_64.msi /qn /l*v install.log
  - start /wait msiexec /i OpenRTM-aist-1.1.2-RELEASE_x86_64.msi /qn /l*v install.log
  - env
  - type install.log

build:

# scripts to run before build
before_build:
  - mkdir build && cd build
  - cmake -G"Visual Studio 14 Win64" ..
  - cmake --build . --config Release
