environment:
  matrix:
    - RTM_VC_VERSION: vc14
    - RTM_VC_VERSION: vc12

platform: x64

clone_folder: c:\projects

configuration:
  - Debug
  - Release

cache:
    - c:\projects\OpenRTM-aist-1.1.2-RELEASE_x86_64.msi

install:
  - ps: Start-FileDownload 'http://openrtm.org/pub/Windows/OpenRTM-aist/1.1/OpenRTM-aist-1.1.2-RELEASE_x86_64.msi'
  - start /wait msiexec /i OpenRTM-aist-1.1.2-RELEASE_x86_64.msi /qn /forcerestart /le "install.log"
  - choco install doxygen.install
  - env
  - type install.log

build:

before_build:
  - mkdir build && cd build
  - if [[ "$(RTM_VC_VERSION)" == "vc14" ]]; then cmake -G "Visual Studio 14 Win64" ..; fi
  - if [[ "$(RTM_VC_VERSION)" == "vc12" ]]; then cmake -G "Visual Studio 12 Win64" ..; fi
