os: Visual Studio 2015

platform: x64

clone_folder: c:\projects

environment:
  RTM_VC_VERSION: 14

install:
  - ps: Start-FileDownload 'http://openrtm.org/pub/Windows/OpenRTM-aist/1.1/OpenRTM-aist-1.1.2-RELEASE_x86_64.msi'
  - start /wait msiexec /i OpenRTM-aist-1.1.2-RELEASE_x86_64.msi /qn /norestart
  - env

build:

before_build:
  - mkdir build && cd build
  - cmake -G"Visual Studio 14 Win64" ..
  - cmake --build . --config Release
