language: cpp
sudo: required

include:
  - os: linux
    dist: trusty
    compiler: gcc

addons:
  apt:
    packages:
    - software-properties-common
    - g++
    - uuid-dev
    - doxygen
    - omniorb-nameserver
    - libomniorb4-dev
    - omniidl

before_install:
  - echo "deb http://openrtm.org/pub/Linux/ubuntu/ trusty main" | sudo tee -a /etc/apt/sources.list
    #  - sudo add-apt-repository -y "deb http://openrtm.org/pub/Linux/ubuntu/ trusty main"
  - sudo apt-get -qq update

install:
  - sudo apt-get install -y --force-yes openrtm-aist
  - sudo apt-get install -y --force-yes openrtm-aist-dev
  - sudo apt-get install -y --force-yes openrtm-aist-example

script:
  - mkdir build && cd build && cmake .. && make
