language: cpp
sudo: required

include:
  - os: linux
    compiler: gcc
  - os: linux
    dist: trusty
    compiler: gcc

env:
  - DIST=precise
  - DIST=trusty

addons:
  apt:
    packages:
    - software-properties-common
    - g++
    - uuid-dev
    - doxygen
    - omniorb-nameserver
    - libomniorb4-dev
    - omniidl

before_install:
  - sudo add-apt-repository -y "deb http://openrtm.org/pub/Linux/ubuntu/ $DIST main"
  - sudo apt-get -qq update

install:
  - sudo apt-get install -y --force-yes openrtm-aist
  - sudo apt-get install -y --force-yes openrtm-aist-dev
  - sudo apt-get install -y --force-yes openrtm-aist-example

script:
  - mkdir build && cd build && cmake .. && make
