language: cpp
sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      env: OPENRTM_REPO="deb http://openrtm.org/pub/Linux/ubuntu/ trusty main"
    - os: linux
      compiler: gcc
      env: OPENRTM_REPO="deb http://openrtm.org/pub/Linux/ubuntu/ precise main"
    - os: linux
      dist: trusty
      compiler: gcc
      env: OPENRTM_REPO="deb http://staging.openrtm.org/pub/Linux/ubuntu/ trusty main"
    - os: linux
      compiler: gcc
      env: OPENRTM_REPO="deb http://staging.openrtm.org/pub/Linux/ubuntu/ precise main"

addons:
  apt:
    packages:
    - software-properties-common
    - g++
    - uuid-dev
    - doxygen
    - omniorb-nameserver
    - libomniorb4-dev
    - omniidl

before_script:
  - echo $OPENRTM_REPO | sudo tee -a /etc/apt/sources.list
  - sudo apt-get -qq update
  - sudo apt-get install -y --force-yes openrtm-aist
  - sudo apt-get install -y --force-yes openrtm-aist-dev
  - sudo apt-get install -y --force-yes openrtm-aist-example

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
