language: cpp
sudo: required

include:
#  - os: linux
#    compiler: gcc
  - os: linux
    dist: trusty
    compiler: gcc

addons:
  apt:
    packages:
    - software-properties-common
    - g++
    - uuid-dev
    - doxygen
    - omniorb-nameserver
    - libomniorb4-dev
    - omniidl

before_install:
  - if [ `grep precise /etc/lsb-release` -eq 0 ]; then export DIST=precise && echo ${DIST}; fi
  - if [ `grep trusty /etc/lsb-release` -eq 0 ]; then export DIST=trusty && echo ${DIST}; fi
  - sudo add-apt-repository -y "deb http://openrtm.org/pub/Linux/ubuntu/ ${DIST} main"
  - sudo apt-get -qq update

install:
  - sudo apt-get install -y --force-yes openrtm-aist
  - sudo apt-get install -y --force-yes openrtm-aist-dev
  - sudo apt-get install -y --force-yes openrtm-aist-example

script:
  - mkdir build && cd build && cmake .. && make
