language: cpp
sudo: required
compiler:
  - gcc
os:
  - linux
dist: trusty
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y software-properties-common
    - sudo add-apt-repository -y "deb http://openrtm.org/pub/Linux/ubuntu/ trusty main"
    - sudo apt-get -qq update
    - sudo apt-get install -y gcc g++ make cmake
    - sudo apt-get install -y omniorb-nameserver
    - sudo apt-get install -y openrtm-aist
    - sudo apt-get install -y openrtm-aist-example
script:
  - mkdir build && cd build && cmake .. && make
